name: steam_analytics

profile: steam_analytics

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  steam_analytics:
    marts:
      +materialized: table
      +static_analysis: strict